---
title: "script"
author: "Yufree"
date: "2016/9/11"
output:
  html_document: default
  pdf_document: default
bibliography: metabolomics.bib
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = T,message=F,warning=F)

# source("https://bioconductor.org/biocLite.R")
# biocLite()
# biocLite('IPO')
# biocLite('xcms')
# biocLite('CAMERA')
# biocLite('sva')
# biocLite('limma')
# install_github("cbroeckl/RAMClustR")
# biocLite('dynamicTreeCut')
# biocLite('fastcluster')
# biocLite('ff')

source('https://raw.githubusercontent.com/yufree/democode/master/meta/getmetadata.R')
source('https://raw.githubusercontent.com/yufree/democode/master/meta/svaplot.R')
source('https://raw.githubusercontent.com/yufree/democode/master/meta/RAW.R')
library(enviGCMS)
```

```{r ParaOpt,eval=F}
mzdatapath <- "./data/day1/qa/"
mzdatafiles <- list.files(mzdatapath, recursive = TRUE, full.names=TRUE)
library(IPO)
peakpickingParameters <- getDefaultXcmsSetStartingParams('centWave')
#setting levels for min_peakwidth to 10 and 20 (hence 15 is the center point)
peakpickingParameters$min_peakwidth <- c(2,10) 
peakpickingParameters$max_peakwidth <- c(15,25)
#setting only one value for ppm therefore this parameter is not optimized
peakpickingParameters$ppm <- 2.5 
resultPeakpicking <- 
  optimizeXcmsSet(files = mzdatafiles[1:4], 
                  params = peakpickingParameters, 
                  nSlaves = 12, 
                  subdir = 'rsm')

optimizedXcmsSetObject <- resultPeakpicking$best_settings$xset

retcorGroupParameters <- getDefaultRetGroupStartingParams()
retcorGroupParameters$profStep <- 1
resultRetcorGroup <-
  optimizeRetGroup(xset = optimizedXcmsSetObject, 
                   params = retcorGroupParameters, 
                   nSlaves = 12, 
                   subdir = "results")


writeRScript(resultPeakpicking$best_settings$parameters, 
             resultRetcorGroup$best_settings, 
             nSlaves=12)
```

## Find the peaks

## analysis the data

```{r}
library(tidyverse)
day1n <- read_csv('results/day1n.csv')
nm <- colnames(day1n)[54:84]
pqf <- day1n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(54:84)
pqfraw <- day1n %>%
        filter(pValues<0.05,qValues<0.05,fold>1.5) %>%
        select(54:84)
pca <- prcomp(t(pqf), center=TRUE, scale=TRUE) 
plot(pca$x[,1],
     pca$x[,2], 
     xlab="PC1",
     ylab="PC2",
     pch=c(rep(1,6),rep(2,7),rep(3,7),rep(4,7),rep(5,4)),
     cex=2,
     main = "PCA-signal")

day7n <- read_csv('results/day7n.csv')
nm <- colnames(day7n)[54:84]
pqf7 <- day7n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(54:84)
pqf7raw <- day7n %>%
        filter(pValues<0.05,qValues<0.05,fold>1.5) %>%
        select(54:84)
pca <- prcomp(t(pqf7), center=TRUE, scale=TRUE) 
plot(pca$x[,1],
     pca$x[,2], 
     xlab="PC1",
     ylab="PC2",
     pch=c(rep(1,6),rep(2,7),rep(3,7),rep(4,7),rep(5,4)),
     cex=2,
     main = "PCA-signal")

day14n <- read_csv('results/day14n.csv')
nm <- colnames(day14n)[54:84]
pqf14 <- day14n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(54:84)
pqf14raw <- day14n %>%
        filter(pValues<0.05,qValues<0.05,fold>1.5) %>%
        select(54:84)
pca <- prcomp(t(pqf14), center=TRUE, scale=TRUE) 
plot(pca$x[,1],
     pca$x[,2], 
     xlab="PC1",
     ylab="PC2",
     pch=c(rep(1,6),rep(2,7),rep(3,7),rep(4,7),rep(5,4)),
     cex=2,
     main = "PCA-signal")

pqf1c <- day1n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day1_con"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf1l <- day1n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day1_low"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf1h <- day1n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day1_high"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))

pqf7c <- day7n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day7_con"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf7l <- day7n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day7_low"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf7h <- day7n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day7_high"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))

pqf14c <- day14n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day14_con"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf14l <- day14n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day14_low"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))
pqf14h <- day14n %>%
        filter(pValuesSv<0.05,qValuesSv<0.05,fold>1.5) %>%
        select(mzmed,rtmed,starts_with("Day14_high"))%>%
        transmute(mzmed = round(mzmed,2),rtmed = round(rtmed),mean1 = rowMeans(select(.,c(3:9))),mean2 = rowMeans(select(.,c(10:16))))

day1 <- setdiff(pqf1, pqf1r)
day7 <- setdiff(pqf7, pqf7r)
day14 <- setdiff(pqf14, pqf14r)

boxp1r <- day1n[2,] %>%
        select(20:50) %>%
        c()%>%
        unlist()
boxp1 <- day1n[2,] %>%
        select(54:84)%>%
        c()%>%
        unlist()
par(mfrow=c(1,2))
boxplot(boxp1r~lv,main='Batch effects')
boxplot(boxp1~lv,main='Batch effects removel')
        
pqf <- pqf1 %>%
        inner_join(pqf7,by = 'mzmed') 
pqf <- pqf %>%
        inner_join(pqf14,by = 'mzmed')
ggplot(pqf, aes(rtmed, mzmed)) + 
  geom_point(show.legend = T) + 
  geom_point(data = pqf,aes(rtmed.x, mzmed), colour = "red",show.legend = T) +
  geom_point(data = pqf,aes(rtmed.y, mzmed), colour = "blue",show.legend = T)
        

ggplot(pqf1c, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf1c$mean2)/5,color='blue') 
ggplot(pqf1l, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf1c$mean2)/5,color='blue')
ggplot(pqf1h, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf1c$mean2)/5,color='blue')

ggplot(pqf7c, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf7c$mean2)/5,color='blue') 
ggplot(pqf7l, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf7c$mean2)/5,color='blue')
ggplot(pqf7h, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf7c$mean2)/5,color='blue')

ggplot(pqf14c, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf14c$mean2)/5,color='blue') 
ggplot(pqf14l, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf14c$mean2)/5,color='blue')
ggplot(pqf14h, aes(rtmed, mzmed)) + 
  geom_point(size=log(pqf14c$mean2)/5,color='blue')
```

```{r eval=F}


library(enviGCMS)

data1 <- getmd('data/positive/day7/control/ctrl_day7_1.mzXML',step = 0.1)
data2 <- getmd('data/positive/day7/control/ctrl_day7_2.mzXML',step = 0.1)
data3 <- getmd('data/positive/day7/control/ctrl_day7_3.mzXML',step=0.1)
data4 <- getmd('data/positive/day7/control/ctrl_day7_4.mzXML',step = 0.1)

datab <- (data1[1:8999,]+data2+data3+data4[1:8999])/4
databsd <- sqrt(((data1[1:8999,]-datab)^2+(data2-datab)^2+(data3-datab)^2+(data4[1:8999,]-datab)^2/3))
databrsd <- databsd/datab
plotsms(datab,databrsd)
plotms(datab)

data5 <- getmd('data/positive/day7/high/high_day7_1.mzXML')
data6 <- getmd('data/positive/day7/high/high_day7_2.mzXML')
data7 <- getmd('data/positive/day7/high/high_day7_3.mzXML')
data8 <- getmd('data/positive/day7/high/high_day7_4.mzXML')

datab <- (data8+data5+data6+data7)/4
databsd <- sqrt(((data8-datab)^2+(data5-datab)^2+(data6-datab)^2+(data7-datab)^2/3))
databrsd <- databsd/datab

plotsms(datab,databrsd)
plotms(datab)

library(reshape2)
library(ggplot2)
gather.matrix <- reshape2:::melt.matrix
ggplot(gather.matrix(t(datab)), aes(Var1,Var2, fill=value))+
        geom_raster()+
        scale_fill_gradient(low = 'red', high = 'yellow', trans='log',name = "Intensity")+
        xlab("Retention time") + 
        ylab("Mass(m/z)") 


hist(log1p(datab),breaks = 100)

data <- 'high_day14_1.mzXML'
data <- xcmsRaw(data,profstep = 1)
        z1 <- data@env$profile
        zf <- as.factor(round(data@scantime))
        df <- aggregate(t(z1), list(zf), sum)[-1]
        rownames(df) <- unique(round(data@scantime))
        colnames(df) <- seq(data@mzrange[1],data@mzrange[2],by = 1)
        d <- t(as.matrix(df))
        

```

## Other methods for batch effect

## RUV

The main idea is use suitable control to remove the batch effect

```{r eval=F}
install.packages("devtools")
library(devtools)
install_github("rwehrens/BatchCorrMetabolomics")
library(BatchCorrMetabolomics)
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite('RUVSeq')
data(BC)
demo(BC, echo = FALSE)

```

```{r}
# fail of interactive progress
df <- groupval(xset3)
library(sva)
lv <- xset3@phenoData[, 1]
mod <- model.matrix(~ lv)
svafit <- sva(df, mod)
```

